coverage:
  status:
    project:
      default:
        # basic
        target: 100%
        threshold: 0%
        flags:
          - unit
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
