coverage:
  status:
    project:
      default:
        # basic
        target: 100%
        threshold: 0%
        flags:
          - unit
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false

comment: # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false # if true: only post the comment if coverage changes
  require_base: no # [yes :: must have a base report to post]
  require_head: yes # [yes :: must have a head report to post]
