import Script from "next/script";
import styles from "./LandingPageTemplate.module.css";
import { Container } from "./components/Container";
import { InlineCode } from "./components/InlineCode";
import { Link } from "./components/Link";
import { Paragraph } from "./components/Paragraph";
import { Section } from "./components/Section";
import { Subtitle } from "./components/Subtitle";
import { TechnologyGrid } from "./components/TechnologyGrid";
import { H1, H2 } from "./components/headings";
import { technologies } from "./technologies";

const LandingPageTemplate = () => {
  return (
    <div className={styles.landingPageTemplate}>
      <style>
        {`
          * {
            box-sizing: border-box;
          }

          html,
          body {
            padding: 0;
            margin: 0;
            font-family: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto,
              Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue,
              sans-serif;
            line-height: 1.5;
          }
        `}
      </style>
      <main>
        <Section>
          <Container center className={styles.headerSection}>
            <H1>
              <span className={styles.textGradient}>Your project is a go!</span>{" "}
              🎉
            </H1>
            <Subtitle>
              Get started by editing <InlineCode>pages/index.tsx</InlineCode>
            </Subtitle>
          </Container>
        </Section>
        <Section>
          <Container className={styles.technologyGridIntro}>
            <H2>Technologies</H2>
            <Paragraph>
              Below you will find an overview of your chosen technologies
              providing you helpful links and simple usage examples to get you
              started.
            </Paragraph>
          </Container>
          <Container wide>
            <TechnologyGrid
              technologies={technologies}
              className={styles.technologyGrid}
            />
          </Container>
        </Section>
      </main>
      <footer>
        <Section>
          <Container center>
            <Paragraph>Generated by Create Next Stack</Paragraph>
          </Container>
        </Section>
      </footer>
    </div>
  );
};

export default LandingPageTemplate;
