import { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";

const Index: NextPage = () => {
  const [result, setResult] = useState(0);

  function add() {
    setResult(result + 1);
  }

  function subtract() {
    setResult(result - 1);
  }

  return (
    <>
      <Head>
        <title>leaflab-next</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <main className="h-screen w-full flex flex-col p-12" data-testid="main">
        <div
          className="bg-gray-100 w-full h-24 rounded-xl mb-12 flex items-center justify-center"
          data-testid="topbar"
        >
          <h1 className="text-xl" data-testid="topbar-content">
            Top Bar
          </h1>
        </div>
        <div
          className="bg-gray-100 rounded-xl w-full h-full flex flex-col items-center justify-center space-y-2"
          data-testid="main-container"
        >
          <h1 className="text-4xl" data-testid="header">
            Project is live
          </h1>
          <h2 className="text-lg text-gray-500" data-testid="subheader">
            Test it now
          </h2>
          <div
            id="calc"
            className="flex space-x-4 items-center"
            data-testid="button-container"
          >
            <button
              data-testid="add-button"
              className="flex items-center justify-center bg-gray-300 rounded hover:bg-gray-400 h-10 w-10"
              onClick={add}
            >
              <p>+</p>
            </button>
            <p data-testid="result">{result}</p>
            <button
              data-testid="subtract-button"
              className="flex items-center justify-center bg-gray-300 rounded hover:bg-gray-400 h-10 w-10"
              onClick={subtract}
            >
              <p>-</p>
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Index;
