import { render, screen } from "@testing-library/react";
import Index from "../pages/index";
import "@testing-library/jest-dom";

describe("Home", () => {
  it("renders a heading", () => {
    render(<Index />);

    const heading = screen.getByRole("heading", {
      name: /Your project is a go!/i,
    });

    expect(heading).toBeInTheDocument();
  });

  test("displays the footer text", () => {
    render(<Index />);
    expect(
      screen.getByText("Generated by Create Next Stack")
    ).toBeInTheDocument();
  });
});
